name: GitHub Pages Deploy

on:
  push:
    paths:
      - "jobs/**"
      - "web/**"
      - ".github/workflows/gh-pages.yaml"
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          token: ${{ secrets.API_KEY_GITHUB_PAGES }}
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install Dependencies
        run: yarn install
      - name: Run Jobs
        run: yarn web
        env:
          API_KEY_COIN_RANKING: ${{ secrets.API_KEY_COIN_RANKING }}
          API_KEY_NEWS: ${{ secrets.API_KEY_NEWS }}
          API_KEY_OPEN_WEATHER: ${{ secrets.API_KEY_OPEN_WEATHER }}
          API_KEY_YOUTUBE: ${{ secrets.API_KEY_YOUTUBE }}
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: web # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
      - name: Telegram
        run: yarn telegram
        env:
          API_KEY_TELEGRAM: ${{ secrets.API_KEY_TELEGRAM }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
